SELECT NOM_POTION,  SUM(COUT_INGREDIENT*QTE) AS COUT_POTION
FROM potion p, ingredient i,compose c
WHERE i.ID_INGREDIENT=c.ID_INGREDIENT
AND  p.ID_POTION = c.ID_POTION
GROUP BY NOM_POTION
ORDER BY COUT_POTION DESC

